name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Determine release type
        id: release_type
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "Tag Name is: $TAG_NAME"
          if [[ $TAG_NAME == *"-alpha"* ]]; then
            echo "RELEASE_TYPE=alpha" >> $GITHUB_ENV
          elif [[ $TAG_NAME == *"-beta"* ]]; then
            echo "RELEASE_TYPE=beta" >> $GITHUB_ENV
          else
            echo "RELEASE_TYPE=normal" >> $GITHUB_ENV
          fi

      - name: Extract tag version
        id: extract_tag_version
        run: echo "TAG_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Update package.json with tag version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ env.TAG_VERSION }}"/' package.json

      - name: Publish package on NPM 📦
        run: |
          echo "Release type is: ${{ env.RELEASE_TYPE }}"
          if [[ "${{ env.RELEASE_TYPE }}" == "alpha" ]]; then
            npm publish --tag alpha
          elif [[ "${{ env.RELEASE_TYPE }}" == "beta" ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
