name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Determine release type
        id: release_type
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          if [[ $TAG_NAME == *"alpha"* ]]; then
            echo "alpha"
          elif [[ $TAG_NAME == *"beta"* ]]; then
            echo "beta"
          else
            echo "normal"
          fi
      - name: Extract tag version
        id: extract_tag_version
        run: echo ::set-output name=tag_version::$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
      - name: Update package.json with tag version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.extract_tag_version.outputs.tag_version }}"/' package.json
      - name: Publish package on NPM 📦
        run: |
          if [[ "${{ steps.release_type.outputs.release_type }}" == "alpha" ]]; then
            npm publish --tag alpha
          elif [[ "${{ steps.release_type.outputs.release_type }}" == "beta" ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
